controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ros_control:  # fixed spelling (optional)
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ros_control:  # match the name used above
  ros__parameters:
    joints:
      - joint1
      - joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

